---
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-Common-net-CIDR
no_index:
  directory:
    - inc
requires:
  Regexp::Common: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.02
